apiVersion: v1
kind: Service
metadata:
  name: sso-service
spec:
  selector:
    app: sso-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP