apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-all
  namespace: ecommerce-dev
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: goose
        image: ghcr.io/sabirkekw/ecommerce_go-goose:latest
        env:
        - name: SSO_DB_STRING
          value: "host=postgres-sso-service user=postgres password=postgres dbname=sso_db sslmode=disable"
        - name: PRODUCTS_DB_STRING
          value: "host=postgres-products-service user=postgres password=postgres dbname=products_db sslmode=disable"
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting SSO DB migrations..."
            goose postgres "$SSO_DB_STRING" up
            
            echo "Starting Products DB migrations..."
            goose postgres "$PRODUCTS_DB_STRING" up
      restartPolicy: OnFailure
  backoffLimit: 4