events {
    worker_connections 1024;  # минимальная настройка
}

http {
    upstream sso-backend {
        server sso-service:8081;
    }
    upstream products-backend {
        server products-service:8080;
    }
    upstream cart-backend {
        server cart-service:8082;
    }
    upstream order-backend {
        server order-service:8083;
    }

    server {
        listen 8000;

        location /v1/auth/ {
            proxy_pass http://sso-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/products/ {
            proxy_pass http://products-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/cart/ {
            proxy_pass http://cart-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/order/ {
            proxy_pass http://order-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }
    }
}